substitutions:
  friendly_name: CHANGEME # the friendly name of your device, can be anything.
  bme680_temperature_offset: 5.8 # this can be changed to calibrate the sensor.
  wifi_output_power: 8.5dB ## you may need to increase this if the esp is far away from your wifi access point. This is the minimal output power and improves the reliability of the motion sensor.

packages:
  ## choose which language you are using by uncommenting the correct line
  # lang: !include lang/de.yaml
  lang: !include lang/en.yaml
  ## choose which sensor you are using by uncommenting the correct line
  # bme680: !include sensors/bme680.yaml
  bme280: !include sensors/bme280.yaml
  hc-sr501: !include sensors/hc-sr501.yaml
  bh1750: !include sensors/bh1750.yaml
  ld2410: !include sensors/ld2410.yaml

esphome:
  name: changeme # the name of your device. It should not contain any special characters or whitespaces. the device can be found in the network by this name.
  friendly_name: ${friendly_name}
  #area: CHANGEME # the area where you deployed the device. optional

## setup the i2c bus and define the pins to use.
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

## this sets up the uart connection to the LD2410B. If you have trouble reading sensor data you may have mixed up rx and tx bins so you can try to change them here.
uart:
  id: ld2410_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
