binary_sensor:
  - platform: gpio
    pin:
      number: ${pin}
      mode:
        input: true
    name: ${label_motion_sensor}
    device_class: motion
    icon: mdi:motion-sensor
    id: motion
    on_state:
      then:
        - script.execute: set_occupied
