sensor:
  - platform: sht4x
    temperature:
      id: temperature
      name: ${label_temperature}
      icon: mdi:thermometer
      filters:
        - offset: !lambda return id(temperature_offset).state;
    humidity:
      id: humidity
      name: ${label_humidity}
      icon: mdi:water-percent
      filters:
        - offset: !lambda return id(humidity_offset).state;
    update_interval: 5s
