globals:
  - id: improv_ble_in_progress
    type: bool
    restore_value: no
    initial_value: "false"

text_sensor:
  - platform: template
    name: ${label_air_quality_state}
    id: air_quality_status
    disabled_by_default: true
    on_value:
      then:
        - script.execute: control_leds

binary_sensor:
  - platform: template
    name: ${label_occupied}
    id: occupied
    icon: mdi:motion-sensor
    on_state:
      then:
        - script.execute: control_leds

switch:
  - platform: template
    id: occupancy_led_automation
    name: ${label_occupancy_automation}
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    on_state:
      then:
        - script.execute: control_leds
  - platform: template
    id: air_quality_led_automation
    name: ${label_air_quality_led_automation}
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    on_state:
      then:
        - script.execute: control_leds

script:
  # Master script controlling the LEDs, based on different conditions : initialization in progress, wifi and api connected and voice assistant phase.
  # For the sake of simplicity and re-usability, the script calls child scripts defined below.
  # This script will be called every time one of these conditions is changing.
  - id: control_leds
    then:
      - lambda: |
          ESP_LOGI("occupied", "control led triggered");

          if (id(improv_ble_in_progress)) {
            id(control_leds_improv_ble_state).execute();
          } else if (!id(wifi_id).is_connected() || !id(api_id).is_connected()){
            id(control_leds_no_ha_connection_state).execute();
          } else if (id(air_quality_led_automation).state && id(air_quality_status).state != ""){
            id(control_leds_air_quality).execute();
          } else if (id(occupancy_led_automation).state && id(occupied).state){
            id(control_leds_occupancy).execute();
          } else {
            id(control_leds_turn_off).execute();
          }
  - id: control_leds_no_ha_connection_state
    then:
      - light.turn_on:
          brightness: 100%
          red: 1
          green: 0
          blue: 0
          id: status_led
          effect: "Fast Pulse"
  - id: control_leds_improv_ble_state
    then:
      - light.turn_on:
          brightness: 100%
          red: 0%
          green: 0%
          blue: 100%
          id: status_led
          effect: "Fast Pulse"
  - id: control_leds_occupancy
    then:
      - lambda: |
          ESP_LOGI("occupied", "Turn on light");
          auto call = id(status_led).turn_on();
          call.set_brightness(1.0);
          call.set_rgb(0.0, 0.0, 1.0);
          call.set_transition_length(0);
          call.perform();
  - id: control_leds_air_quality
    then:
      - lambda: |
          if (id(air_quality_status).state == "critical"){
            ESP_LOGI("air_quality", "Turn on critical light");
            auto call = id(status_led).turn_on();
            call.set_brightness(1.0);
            call.set_rgb(1.0, 0.0, 0.0);
            call.set_effect("Slow Pulse");
            call.perform();
          }else if (id(air_quality_status).state == "warning"){
            ESP_LOGI("air_quality", "Turn on warning light");
            auto call = id(status_led).turn_on();
            call.set_brightness(1.0);
            call.set_rgb(1.0, 0.7, 0.0);
            call.set_effect("Slow Pulse");
            call.perform();
          }
  - id: control_leds_turn_off
    then:
      - light.turn_off:
          id: status_led
          transition_length:
            milliseconds: 0
  - id: set_occupied
    then:
      - lambda: |-
          ESP_LOGI("occupied", "set occupied called");
          if(id(motion).state == true){
            ESP_LOGI("occupied", "set occupied to true");
            id(occupied).publish_state(true);
          }
          if(id(motion).state == false && id(presence).state == false){
            ESP_LOGI("occupied", "set occupied to false");
            id(occupied).publish_state(false);
          }
