packages:
  control_leds: !include "${ './control_leds_air_quality.yaml' if sensor in ('bme680', 'sgp_scd') else './control_leds.yaml'}"

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: id(occupied).publish_state(false);

globals:
  - id: improv_ble_in_progress
    type: bool
    restore_value: no
    initial_value: "false"
  - id: occupied_off_millis
    type: uint32_t
    restore_value: no
    initial_value: "0"

binary_sensor:
  - platform: template
    name: ${label_occupied}
    id: occupied
    icon: mdi:motion-sensor
    device_class: occupancy
    on_state:
      then:
        - lambda: |
            if(id(occupancy_led_automation).state){
              id(control_leds).execute();
            }
    filters:
      - lambda: |
          if(id(occupied).has_state() && x == id(occupied).state){
            return {};
          }
          return x;

switch:
  - platform: template
    id: occupancy_led_automation
    name: ${label_occupancy_automation}
    icon: mdi:lightbulb-auto
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    on_state:
      then:
        - script.execute: control_leds

script:
  - id: control_leds_no_ha_connection_state
    then:
      - light.turn_on:
          brightness: 100%
          red: 1
          green: 0
          blue: 1
          id: status_led
          effect: "Fast Pulse"
  - id: control_leds_improv_ble_state
    then:
      - light.turn_on:
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0%
          id: status_led
          effect: "Fast Pulse"
  - id: control_leds_occupancy
    then:
      - lambda: |
          ESP_LOGI("occupied", "Turn on light");
          auto call = id(status_led).turn_on();
          call.set_brightness(1.0);
          call.set_rgb(1.0, 0.89, 0.8);
          call.set_transition_length(0);
          call.set_effect("none");
          call.perform();
  - id: control_leds_turn_off
    then:
      - light.turn_off:
          id: status_led
          transition_length:
            milliseconds: 0
  - id: set_occupied
    then:
      - lambda: |-
          ESP_LOGI("occupied", "set occupied called");
          if(id(motion).state == true){
            ESP_LOGI("occupied", "set occupied to true");
            id(occupied).publish_state(true);
          } else if(id(presence).state == true && id(occupied).state == false && (millis() - id(occupied_off_millis)) < 10000){
            ESP_LOGI("occupied", "presence returned within 10s of going unoccupied, set occupied to true");
            id(occupied).publish_state(true);
          } else if(id(motion).state == false && id(presence).state == false){
            ESP_LOGI("occupied", "set occupied to false");
            id(occupied_off_millis) = millis();
            id(occupied).publish_state(false);
          }
