name: V2.0

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'V2/**'
      - .github/workflows/v2-0-ci.yml
  push:
    tags:
      - "v2.0*"

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: node:26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: |
            apt-get update
            apt-get install -y chromium fonts-noto-color-emoji
            
      - name: Install md-to-pdf globally
        run: npm i -g md-to-pdf

      - name: Run PDF render script
        working-directory: V2/instructions
        run: |
          chmod +x ./renderPdf.sh
          ./renderPdf.sh

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v7
        with:
          name: v2-instructions-pdf
          path: ./V2/instructions/v2-instructions.pdf
          if-no-files-found: error

  build-bin:
    runs-on: ubuntu-latest
    container:
      image: esphome/esphome:2026.6
    strategy:
      fail-fast: false
      matrix:
        variant: [esp32, esp32supermini]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Compile firmware
        run: | 
          esphome -s apikey "0HkBGFr/oAHaBGVJue84kroMi9UUI+9x/R7dBaUF354=" compile V2/${{ matrix.variant }}.yaml


  release-pdf:
    needs: build-pdf
    if: startsWith(github.ref, 'refs/tags/v2.0') 
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Download PDF Artifact
        uses: actions/download-artifact@v8
        with:
          name: v2-instructions-pdf
          path: .

      - name: Rename Instructions
        run: mv v2-instructions.pdf ${{ github.ref_name }}-instructions.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ github.ref_name }}-instructions.pdf
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

